### ISSUE TITLE
chapter-background.png is referenced in the Makefile as a dependency but does not exist in the repo

### ISSUE THREAD

**Issue by rbarzic** [jd/asciidoc-book-toolchain#1]
make book.printable.pdf 
make: **\* No rule to make target 'chapter-background.png', needed by 'book.printable.pdf'.  Stop.

There are also some other errors but they may be related by my asciidoc installation (Ubuntu 16.04.1 LTS) 

make book.html 
mkdir -p book.html
a2x --icons -d book -D book.html -f xhtml book.txt
a2x: ERROR: missing resource: /home/roba/perso/github/asciidoc-book-toolchain/images/icons/callouts/1.png
Makefile:26: recipe for target 'book.html' failed
make: **\* [book.html] Error 1

**Comment by jd** [comment]
@rbarzic Not sure what's the icon issue is though. Removing the `--icons` might help though.
