### ISSUE TITLE
Ironically, inadequate docs

### ISSUE THREAD

**Issue by tallforasmurf** [jd/asciidoc-book-toolchain#2]
Suggest a book named sample be included with a cover image? So install could be tested right away.

Some linkage to supporting docs e.g. to wherever asciidoc is documented? (Many potential users might know only some markdown flavor, or no text-based markup at all.)

**Comment by jd** [comment]
There's already a sample book you can compile with a sample cover image by just typing `make`, so I don't get your concern?

**Comment by tallforasmurf** [comment]
I looked right past "book.txt" and assumed it was part of the product. So I guess, I suggest 1, rename to example.txt so doofuses like me will see it; have an actual snake.png; have a cover image so one can see how that is linked and experiment with different image resolutions etc. (always an issue in my experience); put all the parts in a folder `example` for convenience.

Also I see that there is a link to asciidoc doc inside book.txt, I still think that should be brought out to the readme level.

**Comment by jd** [comment]
There's a link to Asciidoc in the README. There's a snake.png in img. There's a cover image.

Maybe it'd be good that you actually spend more than 10 seconds looking at a project before opening an issue?
